### PR TITLE
Wait / sync  primitives

### PR DESCRIPTION
**Pull request by giampaolo**
Introduces 3 new options to wait for files and sockets:

```
--wait-for-path=<file>
    Delay start until file or directory appears on disk.

--wait-for-sock=<host:port>
    Delay start until TCP connection succeeds.

--wait-timeout=<secs>
    Timeout for wait-* commands [default: 5].
```

### CODE REVIEW

**Comment by btimby** [comment]
I fixed a ton of merge conflicts. I also refactored this slightly since the wait parameters are only needed at startup, I did not think they needed to be attributes of the object.

**Comment by btimby** [comment]
I also added library level validation. This is duplicated effort (perhaps CLI could catch exceptions from `ReloadConf.__init__()`) but this makes the codebase usable as a library or CLI tool.

**Comment by btimby** [comment]
OK, I am not going to touch this any more. If you are happy with my changes, let me know and I will merge it.

**Comment by giampaolo** [comment]
Great changes! Thanks

**Pull request merged**
